### ISSUE TITLE
Opencanopy Issue

### ISSUE THREAD

**Issue by tlsnine** [dauden/asus-tuf-gaming-z690-6600-tx#1]
Hi. Thanks for the work putting this together.
It works really well.
However, for the life of me I cannot get Opencanopy GUI working.
I've made all the required changes, and even tried adding images and such to the resources folder, yet I still only get the text menu for picking.
Any assistance you can provide would be greatly appreciated!
Thanks again for the efforts!! :)

**Comment by dauden** [comment]
Oh, sorry to here that. but it work well in my side.
let try with new release..

thanks
